apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app: longhorn-manager
  name: longhorn-manager
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    spec:
      - name: longhorn
        hostPath:
          path: /opt/storage/longhorn
