apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      level: INFO
      access:
        enabled: true

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    dashboard:
      enabled: true
      middlewares:
        - name: basic-auth
    api:
      insecure: true
      dashboard: true
